# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "terraform"
    # Location of package manifests
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    target-branch: dependabot